# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('systest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100)),
                ('TestStartDate', models.DateTimeField(blank=True, null=True)),
                ('TestEndDate', models.DateTimeField(blank=True, null=True)),
                ('GoLiveDate', models.DateTimeField(blank=True, null=True)),
                ('system_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='systest.System')),
            ],
        ),
    ]
