# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-06 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systest', '0003_auto_20171006_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testoverview',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='testoverview',
            name='module_id',
        ),
        migrations.DeleteModel(
            name='TestOverview',
        ),
    ]
