# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systest', '0005_testoverview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='ModuleName',
            new_name='module_name',
        ),
        migrations.RenameField(
            model_name='testoverview',
            old_name='ExpectedOutcome',
            new_name='expected_outcome',
        ),
        migrations.RenameField(
            model_name='testoverview',
            old_name='Title',
            new_name='title',
        ),
    ]
