# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systest', '0006_auto_20171009_0947'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Module',
            new_name='SystemModule',
        ),
    ]
