# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systest', '0007_auto_20171009_1219'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SystemModule',
            new_name='Module',
        ),
    ]
