# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-09 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('systest', '0008_auto_20171009_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='GoLiveDate',
            new_name='go_live_date',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='TestEndDate',
            new_name='test_end_date',
        ),
        migrations.RenameField(
            model_name='version',
            old_name='TestStartDate',
            new_name='test_start_date',
        ),
    ]
